name: Node.js CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install dependencies
              run: npm install
              working-directory: ./wip-frontend
            - name: Build
              run: npm run build
              working-directory: ./wip-frontend
            - name: Run lint
              run: npm run lint
              working-directory: ./wip-frontend
            - name: Run tests
              run: npm test
              working-directory: ./wip-frontend
